
apiVersion: v1
kind: Service
metadata:
  name: nginx-web-service
spec:
  selector:
    app: nginx-web
  type: LoadBalancer
  ports:
    - name: http
      port: 8080
      nodePort: 30000
      protocol: TCP