apiVersion: v1
kind: Service
metadata:
  name: nginx-web-app-service
  labels:
    name: nginx-web-app
spec:
  selector:
    app: nginx-web-app
  ports:
    - name: http
      port: 15444
      targetPort: 80
  type: LoadBalancer