apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-web-app
spec:
  selector:
    matchLabels:
      app: nginx-web-app
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx-web-app
    spec:
      containers:
      - name: nginx-web-app
        image: 908905824345.dkr.ecr.eu-west-1.amazonaws.com/udacity-capstone-app-deployment:latest
        ports:
        - containerPort: 80